apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-bar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arthurbdiniz/kind-kong.git
    targetRevision: HEAD
    path: apps/foo-bar
  destination:
    server: https://kubernetes.default.svc
    namespace: foo-bar
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true