apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: "2.8.0"
    chart: kong
    helm:
      parameters:
      - name: "ingressController.installCRDs"
        value: "false"
        forceString: true # ensures that value is treated as a string
      values: |
        podAnnotations:
          prometheus.io/scrape: "true" # Ask Prometheus to scrape the
          prometheus.io/port: "8100"   # Kong pods for metrics
        # plugins:
        #   configMaps:                # change this to 'secrets' if you created a secret
        #   - name: kong-plugin-myheader
        #     pluginName: myheader
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true